site_name: Onqlave Platform
site_author: Onqlave Pty

copyright: Copyright &copy; 2022 - 2023 Onqlave Pty
extra:
    social:
      - icon: material/linkedin
        link: https://www.linkedin.com/company/onqlave/
    generator: false
    version:
      provider: mike
      default: 0.0.1

theme:
  name: material
  logo: img/favicon.ico
  favicon: img/favicon.ico
  font:
    text: Roboto
    code: Roboto Mono
  palette:
    - scheme: default
      primary: black
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: white
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  plugins:
    - search
    - navigation
    - mike:
        alias_type: symlink
        redirect_template: null
        deploy_prefix: ''
        canonical_version: null
        version_selector: true
        css_dir: css
        javascript_dir: js
  features:
    - annouce.dismiss
    - navigation.indexes
    - navigation.footer
    - navigation.instant
    - navigation.tracking
    - navigation.top
    - navigation.path
    - navigation.sections
    - navigation.expand
    - toc.follow
    - search.highlight
    - search.share
    - search.suggest
    - header.autohide

markdown_extensions: 
  - attr_list
  - def_list
  - footnotes
  - toc:
      permalink: true
  

nav:
  - "Home": welcome/welcome.md
  - "Welcome": welcome/welcome.md
  - "Guides":
      - "WebApp Guide":
          - "Authentication": guides/web-app-guide/authentication.md
          - "Dashboard": guides/web-app-guide/dashboard.md
          - "Administration":
              - "Arx": guides/web-app-guide/administration/arx.md
              - "Application": guides/web-app-guide/administration/application.md
              - "API Key": guides/web-app-guide/administration/apikey.md
          - "Platform":
              - "Access": guides/web-app-guide/platform/access.md
      - "CLI Guide":
          - "Overview": guides/cli-guide/overview.md
          - "Authentication": guides/cli-guide/authentication.md
          - "Administration":
              - "Arx": guides/cli-guide/administration/arx.md
              - "Application": guides/cli-guide/administration/application.md
              - "API Key": guides/cli-guide/administration/apikey.md
          - "Platform":
              - "Access": guides/cli-guide/platform/access.md