site_name: Onqlave Platform
nav:
  - Home: index.md
  - 'Welcome':
    - 'Alpha Release': welcome/alpha-release.md
    - 'How does it work?': welcome/how-it-works.md
  - 'Getting Started':
    - 'Features': getting-started/features.md
    - 'Architecture': getting-started/architecture.md
    - 'Product Principles': getting-started/product-principles.md
    - 'Libraries': getting-started/libraries.md
  - 'Guides':
    - 'WebApp vs CLI': guides/web-app-vs-cli.md
    - 'WebApp Guide': guides/web-app-guide.md
    - 'CLI Guide': guides/cli-guide.md
  - 'Resources':
    - 'Glossary': resources/glosary.md
    - 'Pricing': resources/pricing.md
    - 'Blogs': resources/blogs.md
    - 'OpenAPI Docs': resources/open-api-doc.md
    - 'OpenAPI Specs': resources/open-api-spec.md
  - 'Others':
    - 'Change Log': others/change-log.md
    - 'API Status': others/api-status.md
  
theme: readthedocs
